### ISSUE TITLE
Fix Windows path handling in cardsheets

### ISSUE THREAD

**Issue by Lucretiel** [TI4-Online/TI4-TTPG#12]
I've run into several cases where cardsheet code presumes POSIX paths, using a `/` separator, leading to test or script failures when running on Windows (for instance: https://github.com/TI4-Online/TI4-TTPG/pull/11/files#diff-e3b913cfb1ac4116acb4d8a683605082ad6a633ce307e7b41864771ca66f6f2d). Path handling should be fixed to use node's `path` module for cross-platform behavior:

- Use `path.normalize` to deal with hardcoded path strings
- Use `path.sep` as the path separator
- Use `.split(path.sep)` to process directory components
- Etc

**Comment by darrellanderson** [comment]
I checked in a cleanup/organziation/testing change to cardsheets.js, now all the file path management _should_ be consolidated inside "class AssetFilenames".

**Comment by darrellanderson** [comment]
(checked in what I hope is the fix, I can't test b/c I'm on a posix setup)

**Comment by Lucretiel** [comment]
Thanks! I'll test it tonight

**Comment by darrellanderson** [comment]
fixed
