### ISSUE TITLE
Strategy Card Card Selector over Savant

### ISSUE THREAD

**Issue by GraemeMurphy** [TI4-Online/TI4-TTPG#457]
Latest game has the card selector for the strategy cards overlaying the Savant helper obstructing its use

![image](https://github.com/TI4-Online/TI4-TTPG/assets/144836340/3e623cf5-ced7-4c64-b1af-03493f976a6b)

![TI4 Strategy Card Issue](https://github.com/TI4-Online/TI4-TTPG/assets/144836340/89b3c9b8-549f-46e3-92c7-f63fe82b0ac3)

**Comment by darrellanderson** [comment]
The strategy card mat has moved, if you load a new game it'll be rotated and "below" the savant.

If you're loading an old save you can unlock the mat and move it manually, sorry for the inconvenience.

**Comment by GraemeMurphy** [comment]
Thanks Darryl for the swift response, still getting used to TTPG (Game 3 or 4).   Think its sorted.  Will find out next Monday when we play what hopefully is the last turn.

***@***.***
