### ISSUE TITLE
Custodia Vigilia PDS

### ISSUE THREAD

**Issue by GraemeMurphy** [TI4-Online/TI4-TTPG#463]
Completed our game on TTPG last night but discovered that when Keleres fired their PDSII from Mecatol it wasn't including the bonus space cannon 5 for Custodia Vigilia.

**Comment by GraemeMurphy** [comment]
Darrell

Thanks for the info - eventually got it to work (not knowing which side of the token is the PDS side etc)

***@***.***

To be honest it seems a bit clunky and intuitive.  The system should have all the info it needs to do this automatically.


  1.  Is it the Keleres firing their space cannon ?
  2.  Do the Keleres have the Mecatol card in their play area ?
  3.  Do they have the Custodia Vigilia card in their play area
  4.  Then act out the usual algorithms for PDS fire (Plasma Scoring, PDS II etc)

This would save finding a token (That many might know exists) and then wondering if you've got it on the correct side.

Do'able ?

One thing I noted from the above, and that players in the game will quickly spot, is that Plasma Scoring gains an extra die and a player would have added that die to the CV space cannon as it hits on a 5 rather than the 6 the others were hitting on.

Really enjoying playing TI on TTPG - you are doing a fantastic job with this and I for one really appreciate the work you are putting into this project.

Best Wishes
Graeme

**Comment by darrellanderson** [comment]
The current solution is the same way Titan's hero works (the token grants the power), but we can rework Custodia Vigilia to look at cards instead.

**Comment by darrellanderson** [comment]
Added.  It appears plasma scoring is already working for Custodia Vigilia.

**Comment by darrellanderson** [comment]
Also it's worth noting this checks for (1) the Custodia Vigilia legendary planet card and (2) Mecatol Rex planet card in the play area.  It does NOT check if the rolling faction is Keleres in order to work with Franken games.
