### ISSUE TITLE
CI pipeline

### ISSUE THREAD

**Issue by Lucretiel** [TI4-Online/TI4-TTPG#8]
We should use GitHub Actions to ensure that code continues to pass our quality requirements- pass tests, lint, etc. These actions should be set up to run against incoming pull requests.

**Comment by darrellanderson** [comment]
100% for this, no idea how to set it up.  If you / someone has experience with this let's do it!

**Comment by Lucretiel** [comment]
I know how & am happy to do it, but I'd need to be added to the GitHub repo as a maintainer. I'll set it up first on my own fork just to demonstrate that I know how to do it.

**Comment by darrellanderson** [comment]
Terrific!
